spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc  # Replace with your database name
    username: root                               # Replace with your MySQL username
    password: Licious@123                               # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none                                    # Options: none, validate, update, create, create-drop
    show-sql: true                                        # Enables SQL logging in the console
    properties:
      hibernate:
        format_sql: true                                  # Formats SQL output in a readable way
        dialect: org.hibernate.dialect.MySQL8Dialect      # Replace based on your MySQL version (e.g., MySQL5Dialect)